*** Settings ***
Documentation       Dynamic Controls Locators


*** Variables ***
${CHECKBOX}                [id="checkbox-example"] input[type='checkbox']
${TOGGLE_CHECKBOX_BUTTON}  [id="checkbox-example"] button
${CHECKBOX_MESSAGE}        [id="checkbox-example"] [id="message"]
${INPUT_FIELD}             [id="input-example"] input[type='text']
${TOGGLE_INPUT_BUTTON}     [id="input-example"] button
${INPUT_MESSAGE}           [id="input-example"] [id="message"]
