*** Settings ***
Documentation       Dynamic Controls Locators


*** Variables ***
${CHECKBOX}                #checkbox-example input[type='checkbox']
${TOGGLE_CHECKBOX_BUTTON}  #checkbox-example button
${CHECKBOX_MESSAGE}        #checkbox-example #message
${INPUT_FIELD}             #input-example input[type='text']
${TOGGLE_INPUT_BUTTON}     #input-example button
${INPUT_MESSAGE}           #input-example #message
