*** Settings ***
Documentation       Dynamic Controls Locators


*** Variables ***
${CHECKBOX}                css:#checkbox-example input[type='checkbox']
${TOGGLE_CHECKBOX_BUTTON}  css:#checkbox-example button
${CHECKBOX_MESSAGE}        css:#checkbox-example #message
${INPUT_FIELD}             css:#input-example input[type='text']
${TOGGLE_INPUT_BUTTON}     css:#input-example button
${INPUT_MESSAGE}           css:#input-example #message
